UPDATE person SET first_name = NULL where LENGTH(first_name) = 0;
UPDATE person SET last_name = NULL where LENGTH(last_name) = 0;
UPDATE person SET middle_name = NULL where LENGTH(middle_name) = 0;
UPDATE person SET badge_number = NULL where LENGTH(badge_number) = 0;
UPDATE person SET badge_number = NULL where badge_number = 0;
UPDATE person SET street = NULL where LENGTH(street) = 0;
UPDATE person SET city = NULL where LENGTH(city) = 0;
UPDATE person SET state = NULL where LENGTH(state) = 0;
UPDATE person SET zip = NULL where LENGTH(zip) = 0;
UPDATE person SET phone = NULL where LENGTH(phone) = 0;
UPDATE person SET reg_type = NULL where LENGTH(reg_type) = 0;
UPDATE person SET rpga_number = NULL where LENGTH(rpga_number) = 0;
UPDATE person SET email_address = NULL where LENGTH(email_address) = 0;
UPDATE person SET country = NULL where LENGTH(country) = 0;
UPDATE person SET convention_id = 1;